export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { CartProvider } from "./components/cart/CartContext";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";
import { FavoProvider } from "./components/favorites/FavoContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <CartProvider>
          <FavoProvider>
        <Header />
          <main className="flex-grow">{children}</main>
          </FavoProvider>
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
