export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { CartProvider } from "./components/cart/CartContext";
import Header from "./components/Header";
import Footer from "./components/Footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header />
        <CartProvider>
          <main className="flex-grow">{children}</main>
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
